package ca.ryerson.rnet.ls3.si;

import ca.ryerson.rnet.ls3.annotation.OwlIriFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.ResourceFactory;
import org.w3.www.owl.Thing;
import org.w3.www.time.Instant;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 Source Class: AssaultWithWeapon <br>
 * @version generated on Wed Dec 10 20:15:16 EST 2014 by Hossein Fani  <https://sites.google.com/site/hosseinfani at ls3.rnet.ryerson.ca>
 */

public class AssaultWithWeapon extends Assault {

    public AssaultWithWeapon(Instant time, Instant reportedTime, Thing weapon) {
        super(time, reportedTime);
        this.weapon = weapon;
    }
    /* ***************************************************
     * Property http://ls3.rnet.ryerson.ca/ontologies/sio/weapon
     */
    private Thing weapon;
    public Thing getWeapon(){
        return weapon;
    }

    @Override
    public Resource getRdfResource() throws ClassNotFoundException {
        Resource r = super.getRdfResource();
        if(weapon != null){
            r.getModel().add(weapon.getRdfResource().getModel());
            Property s = ResourceFactory.createProperty(OwlIriFactory.getIri(this.getClass(), "weapon"));
            Resource o = ResourceFactory.createResource(OwlIriFactory.getIri(weapon.getId()));
            r.addProperty(s, o);
        }
        
        return r;
    }
}
