package ca.ryerson.rnet.ls3.si;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Color <br>
 * @version generated on Wed Dec 10 20:15:16 EST 2014 by Hossein Fani  <https://sites.google.com/site/hosseinfani at ls3.rnet.ryerson.ca>
 */

public enum Color {
    Red("http://www.w3.org/2006/03/wn/wn20/instances/word-red"),
    Blonde("http://www.w3.org/2006/03/wn/wn20/instances/word-blonde"),
    Black("http://www.w3.org/2006/03/wn/wn20/instances/word-black");

    
    private final String iri;
    Color(String iri){
        this.iri = iri;
    }
    public String getIri(){
        return iri;
    }
}
