package ca.ryerson.rnet.ls3.si;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: ProximityAdverb <br>
 * @version generated on Wed Dec 10 20:15:17 EST 2014 by Hossein Fani  <https://sites.google.com/site/hosseinfani at ls3.rnet.ryerson.ca>
 */

public enum ProximityAdverb{
    Approximitaly("http://www.w3.org/2006/03/wn/wn20/instances/word-approximately"),
    Early("http://www.w3.org/2006/03/wn/wn20/instances/word-early"),
    After("http://www.w3.org/2006/03/wn/wn20/instances/word-after");
    
    private final String iri;
    ProximityAdverb(String iri){
        this.iri = iri;
    }
    public String getIri(){
        return iri;
    }
    
}
