package ca.ryerson.rnet.ls3.si;

import ca.ryerson.rnet.ls3.annotation.OwlIriFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.ResourceFactory;
import java.util.ArrayList;
import java.util.List;
import org.w3.www.time.Instant;
import org.purl.event.Event;
import org.w3.www.owl.Thing;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: SecurityIncident <br>
 * @version generated on Wed Dec 10 20:15:17 EST 2014 by Hossein Fani <https://sites.google.com/site/hosseinfani at ls3.rnet.ryerson.ca>
 */

public class SecurityIncident extends Event {

    public SecurityIncident(Instant time, Instant reportedTime){
        super(time);
        reportedInstant = reportedTime;
    }
    /* ***************************************************
     * Property http://ls3.rnet.ryerson.ca/ontologies/sio/Related
     */
    private  List<SecurityIncident> related = new ArrayList<>(); 
    public List<SecurityIncident> getRelated(){
        return related;
    }

    /* ***************************************************
     * Property http://ls3.rnet.ryerson.ca/ontologies/sio/reportedInstant
     */
    private Instant reportedInstant; 
    public Instant getReportedInstant(){
        return reportedInstant;
    }

    /* ***************************************************
     * Property http://ls3.rnet.ryerson.ca/ontologies/sio/finalState
     */
    private Thing finalState;
    public Thing getFinalState(){
        return finalState;
    }

    @Override
    public Resource getRdfResource() throws ClassNotFoundException {
        Resource r = super.getRdfResource();
        for(Thing t : related){
            r.getModel().add(t.getRdfResource().getModel());
            Property s = ResourceFactory.createProperty(OwlIriFactory.getIri(this.getClass(), "related"));
            Resource o = ResourceFactory.createResource(OwlIriFactory.getIri(t.getId()));
            r.addProperty(s, o);
        }
        if(reportedInstant != null){
            r.getModel().add(reportedInstant.getRdfResource().getModel());
            Property s = ResourceFactory.createProperty(OwlIriFactory.getIri(this.getClass(), "reportedInstant"));
            Resource o = ResourceFactory.createResource(OwlIriFactory.getIri(reportedInstant.getId()));
            r.addProperty(s, o);
        }
        if(finalState != null){
            Property s = ResourceFactory.createProperty(OwlIriFactory.getIri(this.getClass(), "finalState"));
            r.addLiteral(s, finalState);
        }
        
        return r;
    }
}
