package ca.ryerson.rnet.ls3.si;

import com.xmlns.foaf.Organization;
import java.util.List;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: SecurityService <br>
 * @version generated on Wed Dec 10 20:15:17 EST 2014 by  Hossein Fani  <https://sites.google.com/site/hosseinfani at ls3.rnet.ryerson.ca>
 */

public class SecurityService extends Organization {

    public SecurityService(String name, List<Integer> age, ProximityAdverb ageProximityAdverb) {
        super(name, age, ageProximityAdverb);
    }


}
