package ca.ryerson.rnet.ls3.si;

import java.util.List;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Student <br>
 * @version generated on Wed Dec 10 20:15:17 EST 2014 by Hossein Fani <https://sites.google.com/site/hosseinfani at ls3.rnet.ryerson.ca>
 */

public class Student extends CommunityMember {

    public Student(String name, List<Integer> age, ProximityAdverb ageProximityAdverb, String gender, String wearing, String carrying) {
        super(name, age, ageProximityAdverb, gender, wearing, carrying);
    }


}
