package ca.ryerson.rnet.ls3.si;

import org.w3.www.time.Instant;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Voyeurism <br>
 * @version generated on Wed Dec 10 20:15:17 EST 2014 by Hossein Fani <https://sites.google.com/site/hosseinfani at ls3.rnet.ryerson.ca>
 */

public class Voyeurism extends SecurityIncident {

    public Voyeurism(Instant time, Instant reportedTime) {
        super(time, reportedTime);
    }

}
