package com.xmlns.foaf;

import ca.ryerson.rnet.ls3.annotation.OwlIri;
import ca.ryerson.rnet.ls3.annotation.OwlIriFactory;
import ca.ryerson.rnet.ls3.si.ProximityAdverb;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.ResourceFactory;
import java.util.ArrayList;
import java.util.List;
import org.w3.www.owl.Thing;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Agent <br>
 * @version generated on Wed Dec 10 20:15:17 EST 2014 by Hossein Fani  <https://sites.google.com/site/hosseinfani at ls3.rnet.ryerson.ca>
 */

public class Agent extends Thing{

    public Agent(String name, ProximityAdverb ageProximityAdverb, String gender){
        this.name = name;
        ageProximity = ageProximityAdverb;
        this.gender = gender;
    }
    
    private String name;
    public String getName(){
        return name;
    }
    
    private List<Integer> age = new ArrayList<>();
    public List<Integer> getAge(){
        return age;
    }
    /* ***************************************************
     * Property http://ls3.rnet.ryerson.ca/ontologies/sio/ageProximity
     */
    @OwlIri
    private ProximityAdverb ageProximity;
    public ProximityAdverb getAgeProximity(){
        return ageProximity;
    }
    
    private String gender;
    public String getGender(){
        return gender;
    }
    
    @Override
    public Resource getRdfResource() throws ClassNotFoundException {
        Resource r = super.getRdfResource();
        if(ageProximity != null){
            Property s = ResourceFactory.createProperty(OwlIriFactory.getIri(this.getClass(), "ageProximity"));
            Resource o = ResourceFactory.createResource(ageProximity.getIri());
            r.addProperty(s, o);
        }
        if(name != null){
            Property s = ResourceFactory.createProperty(OwlIriFactory.getIri(this.getClass(), "name"));
            r.addLiteral(s, name);
        }
        for(Integer a : age){
            Property s = ResourceFactory.createProperty(OwlIriFactory.getIri(this.getClass(), "age"));
            r.addLiteral(s, a);
        }
        if(gender != null){
            Property s = ResourceFactory.createProperty(OwlIriFactory.getIri(this.getClass(), "gender")); 
            r.addLiteral(s, gender);
        }
        return r;
    }
}
