package com.xmlns.foaf;

import ca.ryerson.rnet.ls3.si.ProximityAdverb;
import java.util.List;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Organization <br>
 * @version generated on Wed Dec 10 20:15:17 EST 2014 by Hossein Fani  <https://sites.google.com/site/hosseinfani at ls3.rnet.ryerson.ca>
 */

public class Organization extends Agent {

    public Organization(String name, List<Integer> age, ProximityAdverb ageProximityAdverb) {
        super(name, ageProximityAdverb, null);
    }

}
